CREATE DATABASE diplomski;

USE diplomski;

CREATE TABLE "User"(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	password varchar(60) not null
);