CREATE DATABASE diplomski;

USE diplomski;

CREATE TABLE "User"(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	password varchar(60) not null
);

CREATE TABLE Profesor (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	ime varchar(255) NOT NULL,
	prezime varchar(255) NOT NULL,
	is_saradnik BOOLEAN NOT NULL DEFAULT false,
	email varchar(255)
);

CREATE TABLE Predmet (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sifra varchar(255) NOT NULL UNIQUE,
	naziv varchar(255) NOT NULL,
	godina INT NOT NULL,
	semestar varchar(255) NOT NULL,
	status varchar(1) NOT NULL,
	profesor_id INT REFERENCES Profesor(id)
);

CREATE TABLE Ispit (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
predmet_id INT REFERENCES Predmet(id),
datum DATE NOT NULL,
vreme TIME NOT NULL,
is_ispit BOOLEAN
);

CREATE TABLE Dezurstva (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ispit_id INT REFERENCES Ispit(id),
saradnik_id INT REFERENCES Profesor(id)
);

INSERT INTO Profesor (ime,prezime, is_saradnik, email) VALUES('Proba','Probic',false,'proba@gmail.com');
INSERT INTO Profesor (ime,prezime, is_saradnik, email) VALUES('Nikola','Jevremovic',true,'n.jevremovic@gmail.com');
INSERT INTO Profesor (ime,prezime, is_saradnik, email) VALUES('Luka','Vuksanovic',true,'l.vuksanovic@gmail.com');
INSERT INTO Profesor (ime,prezime, is_saradnik, email) VALUES('Visnja','Simic',false,'v.simic@gmail.com');
INSERT INTO Profesor (ime,prezime, is_saradnik, email) VALUES('Tatjana','Stojanovic',false,'t.stojanovic@gmail.com');

INSERT INTO Predmet (naziv,godina,semestar,status,sifra,profesor_id) VALUES ('Osnivi probe 1',1,'zimski','I','PR0BA75',1);
INSERT INTO Predmet (naziv,godina,semestar,status,sifra,profesor_id) VALUES ('Računarski sistemi',1,'zimski','O','19.INF034',4);
INSERT INTO Predmet (naziv,godina,semestar,status,sifra,profesor_id) VALUES ('Strukture podataka i algoritmi',1,'letnji','O','19.INF037',5);
INSERT INTO Predmet (naziv,godina,semestar,status,sifra,profesor_id) VALUES ('Uvod u veštačku inteligenciju', 3,'zimski','O','19.IN1027',4);
INSERT INTO Predmet (naziv,godina,semestar,status,sifra,profesor_id) VALUES ('Logičko i funkcijsko programiranje',3,'letnji','O','19.FI2023',5);

INSERT INTO Ispit (predmet_id, datum, vreme, is_ispit) VALUES (1,'2026-08-15','08:00:00',true);
INSERT INTO Ispit (predmet_id, datum, vreme, is_ispit) VALUES (2,'2026-08-2','09:00:00',true);
INSERT INTO Ispit (predmet_id, datum, vreme, is_ispit) VALUES (3,'2026-08-10','14:00:00',true);
INSERT INTO Ispit (predmet_id, datum, vreme, is_ispit) VALUES (4,'2026-07-29','10:00:00',true);
INSERT INTO Ispit (predmet_id, datum, vreme, is_ispit) VALUES (5,'2026-07-24','09:00:00',true);